package com.team3.holiday.tasks;

public class TaskTwoHtml {

    private static final String HTML_SECOND_TASK = "<!DOCTYPE html><html><head><meta charset=\"UTF-8\"><style>p {margin: 20px 0;}.first_p {margin-top: 0;}.container {position: relative;border: 1px solid black;background-color: white;box-shadow: 4px 4px 0px black;padding: 20px;margin-bottom: 20px;}.num {position: absolute;top: 0;left: 0;padding: 2px 9px;border-right: 1px solid black;border-bottom: 1px solid black;}.warn_notif {background-color: #FFE7D6;color: #FF5C00;padding: 20px;margin: 0 auto;margin-bottom: 40px;}.code {font-weight: 600;background-color: #DEDEDE;padding: 10px 20px;width: max-content;margin: 0 auto;}</style></head><body style=\"font-family: Lucida Console, Monaco, Monospace; line-height: 150%;  text-align: center; font-size: 12px;\"><h2 style=\"margin-bottom: 40px; margin-top: 40px;\">День 2<br>\"Салатный\"</h2><div class=\"warn_notif\">Внимательно прочитайте задание до конца <br> прежде чем приступить к выполнению</div><div class=\"container\"><div class=\"num\">1</div>Давным-давно в Практикуме был студент, легенды о котором ходят и по сей день: он одновременно проходил курсы \"Java-разработчик\",\"React-разработчик\", а также \"Нагрузочное тестирование\" и \"Английский для IT\".<br>Как говорится, был <s>и швец, и жнец, и на дуде игрец</s> фулстек-разработчик.<br>Однажды он куда-то пропал, но оставил кучу непонятных записок.<br>Взгляните сами:<br><code id=\"message\"><span>{&quot;encoded&quot;: &quot;TMHQ M RUZQ DQMOF OAPUZS PMK&quot;, &quot;offset&quot;: &quot;12&quot;}</span></code></div><div class=\"container\"><div class=\"num\">2</div>Мы уже устали их хранить, поэтому каждые <span>7</span> секунд отправляем очередную записку в шредер.<br>Попробуйте обновить страницу - скорее всего старая записка уже уничтожена, а на ее месте новая.</div><div class=\"container\"><div class=\"num\">3</div><p>Помогите нам понять тайный смысл хотя бы одной из этих записок пока шредер не разобрался с ней 🗳<br><br>Ответ присылайте сюда:</p><div class=\"code\">POST http://ya.praktikum.fvds.ru:8080/dev-day/task/2</div><p>В тело положите json:</p><code>{\"decoded\": \"текст\"}</code><p>А, да, вы должно быть заметили, что мы обновили протоколы безопасности.<br> Поэтому всегда кладите в HTTP-header AUTH_TOKEN токен вашей команды.</p></div><div class=\"container\"><div class=\"num\">4</div>В знак благодарности мы пришлем вам <b><span style=\"color: #21B409;\">200 OK</span></b> и json со ссылкой на следующее задание в таком виде:<br><code>{\"nextTaskUrl\": \"http://...\", \"message\": \"...\", \"completed\": true}</code><br>Но вот если шредер опередит вас, то вы получите <b><span style=\"color: #d56109;\">400 BAD REQUEST</span></b>, а записку придется получить заново.</div><p style=\"margin: 40px 0;\"><b> Увидимся завтра! :)</b></p></body></html>";

    public static String getTempSecondTask() {
        return HTML_SECOND_TASK;
    }
}
